config/routes.rb
Rails.application.routes.draw do
  get 'reviews/new'
  resources :housings do
    resources :reviews, only: %i[create]
    resources :books, only: %i[create]
    resources :bookings

  end

  resources :books, only: %i[index]



  #shallow
  devise_for :users
  root to: "pages#home"
  get '/books', to: 'books#index'


  get '/books', to: 'books#index'
  post '/books', to: 'books#create'
  get '/books/new', to: 'books#new', as: 'new_book'
  get '/books/:id/edit', to: 'books#edit', as: 'edit_book'
  get '/books/:id', to: 'books#show', as: 'book'
  patch '/books/:id', to: 'books#update'
  put '/books/:id', to: 'books#update'
  delete '/books/:id', to: 'books#destroy'

  #get '/home', to: 'pages#home'
  # post '/offers', to: 'offers#index'
  # post '/products', to: 'products#create'
  # put '/products/:id', to: 'products#update'
  # delete '/products/:id', to: 'products#destroy'
  # post '/bookings', to: 'bookings#create'
  # post '/reviews', to: 'reviews#create'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
 #get '/housings', to: 'housings#index', as: 'housings'

  # get 'pages/example', to: 'pages#example'
  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/shared/_card.html.erb
<%= link_to housing_path(housing), class:'text-decoration-none' do %>
  <div id="card">
    <%# This div would be the image %>
    <div class="w-100" style='background-image: url("<%= cl_image_path(housing.image.key) %>"); background-size: cover; background-repeat: no-repeat; background-position: center center; height: 250px; border-radius: 10px;'></div>

    <div id="d-flex content" class="mt-4" style="flex-direction: column; align-items: flex-start;">
      <%# Nombre del housing %>
      <h4 class="text-black"><%= housing.name %></h4>

      <%# Nombre de la ciudad %>
      <p id="city" style="margin-bottom: 1px; color: gray;"><%= housing.city %></p>
      <div>
          <i class="fas fa-star star-yellow opacity-50" style="color: gray;"></i>
          <small><em class="text-secondary"><%= housing.averagee_rating %></em></small>
      </div>
      <%# Fechas disponibles %>
      <p id="availability" style="margin-bottom: 8px; color: gray;">Oct 23 - 28</p>

      <%# Precio por noche %>
      <div id="pricepernight" class='d-flex align-items-end gap-1' style="color: black;">
        <h5 style="margin-bottom: 4px;">$<%= housing.price %></h5>
        <p style="margin-bottom: 2px;">/ night</p>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<!-- Footer -->
<footer class="text-center text-muted pt-2 mt-5" style="background-color: #FBFBFB;">
<!-- Section: Links  -->
  <section>
    <div class="mx-5 text-md-start mt-5">
      <!-- Grid row -->
      <div class="mx-5 d-flex justify-content-between mt-3">
        <div>
          <h6 class="text-black mb-4">
            Support
          </h6>
          <p>
            <a href="#!" class="text-reset text-decoration-none">Help Center</a>
          </p>
          <p>
            <a href="#!" class="text-reset text-decoration-none">Safety Information</a>
          </p>
          <p>
            <a href="#!" class="text-reset text-decoration-none">Cancellation Options</a>
          </p>
          <p>
            <a href="#!" class="text-reset text-decoration-none">Our COVID-19 Response</a>
          </p>
          <p>
            <a href="#!" class="text-reset text-decoration-none">Supporting people with disabilities</a>
          </p>
          <p>
            <a href="#!" class="text-reset text-decoration-none">Report a neighborhood concern</a>
          </p>
        </div>
        <div>
          <h6 class="text-black mb-4">
            Community
          </h6>
          <p>
            <a href="#!" class="text-reset text-decoration-none">Aribnb.org: disaster relief housing</a>
          </p>
          <p>
            <a href="#!" class="text-reset text-decoration-none">Support: Afghan refugees</a>
          </p>
          <p>
            <a href="#!" class="text-reset text-decoration-none">Celebrating diversity & belonging</a>
          </p>
          <p>
            <a href="#!" class="text-reset text-decoration-none">Combating discrimination</a>
          </p>
        </div>
        <div>
          <h6 class="text-black mb-4">
            Hosting
          </h6>
          <p>
            <a href="#!" class="text-reset text-decoration-none">Try hosting</a>
          </p>
          <p>
            <a href="#!" class="text-reset text-decoration-none">AirCover: protection for Hosts</a>
          </p>
          <p>
            <a href="#!" class="text-reset text-decoration-none">Explore hosting resources</a>
          </p>
          <p>
            <a href="#!" class="text-reset text-decoration-none">Visit our community forum</a>
          </p>
          <p>
            <a href="#!" class="text-reset text-decoration-none">How to host responsibly</a>
          </p>
        </div>
        <div>
          <h6 class="text-black mb-4">
            About
          </h6>
          <p>
            <a href="#!" class="text-reset text-decoration-none">Newsroom</a>
          </p>
          <p>
            <a href="#!" class="text-reset text-decoration-none">Learn about new features</a>
          </p>
          <p>
            <a href="#!" class="text-reset text-decoration-none">Letter from our founders</a>
          </p>
          <p>
            <a href="#!" class="text-reset text-decoration-none">Careers</a>
          </p>
          <p>
            <a href="#!" class="text-reset text-decoration-none">Investors</a>
          </p>
          <p>
            <a href="#!" class="text-reset text-decoration-none">Airbnb Luxe</a>
          </p>
        </div>
      </div>
      <hr class="mx-5 mt-5">
      <!-- Grid row -->
    </div>
  </section>
  <!-- Section: Links  -->


  <!-- Copyright -->
  <div class="justify-content-between mx-5 pb-5">
    <div class="mx-5 pt-5 d-flex justify-content-between align-items-center">
    <%# Copyright %>
      <div class="d-flex gap-2 align-items-center">
        <p>
          © 2023 Airbnb, Inc.
        </p>
        <p>
          ·
        </p>
        <p>
          Terms
        </p>
        <p>
          ·
        </p>
        <p>
          Sitemap
        </p>
        <p>
          ·
        </p>
        <p>
          Privacy
        </p>
        <p>
          ·
        </p>
        <p>
          Your Privacy Choices
        </p>
        <svg class="mb-3" width="26" height="16" fill="none"><rect x="0.5" y="0.5" width="25" height="11" rx="5.5" fill="#fff"></rect><path d="M14 1h7a5 5 0 010 10H11l3-10z" fill="#06F"></path><path d="M4.5 6.5l1.774 1.774a.25.25 0 00.39-.049L9.5 3.5" stroke="#06F" stroke-linecap="round"></path><path d="M16.5 3.5L19 6m0 0l2.5 2.5M19 6l2.5-2.5M19 6l-2.5 2.5" stroke="#fff" stroke-linecap="round"></path><rect x="0.5" y="0.5" width="25" height="11" rx="5.5" stroke="#06F"></rect></svg>
      </div>
      <%# Social Media %>
      <div class="d-flex gap-4 align-items-center pb-4">
        <div class="d-flex gap-4 mx-4">
          <!-- Language -->
          <div class="d-flex align-items-center gap-2">
            <i class="fas fa-lg fa-globe"></i>
            <a class="text-muted">English (US)</a>
          </div>

          <!-- Currency -->
          <div class="d-flex align-items-center gap-2">
            <i class="fas fa-lg fa-dollar-sign"></i>
            <a class="text-muted">USD</a>
          </div>
        </div>

        <!-- Facebook -->
        <i class="fab fa-lg fa-facebook-f"></i>

        <!-- Twitter -->
        <i class="fab fa-lg fa-twitter"></i>

        <!-- Instagram -->
        <i class="fab fa-lg fa-instagram"></i>
      </div>
    </div>
  </div>
</footer>
<!-- Footer -->

app/views/shared/_logo.html.erb
<div class="logo">
	<div class="logo__top"></div>
	<div class="logo__sides"></div>
	<div class="logo__loop">
		<span></span>
		<span></span>
		<span></span>
	</div>
	<div class="logo__corners">
		<span></span>
		<span></span>
	</div>
</div>