config/routes.rb
Rails.application.routes.draw do
  get 'reviews/new'
  resources :housings do
    resources :reviews, only: %i[create]
    resources :books, only: %i[create]
    resources :bookings

  end

  resources :books, only: %i[index]



  #shallow
  devise_for :users
  root to: "pages#home"
  get '/books', to: 'books#index'


  get '/books', to: 'books#index'
  post '/books', to: 'books#create'
  get '/books/new', to: 'books#new', as: 'new_book'
  get '/books/:id/edit', to: 'books#edit', as: 'edit_book'
  get '/books/:id', to: 'books#show', as: 'book'
  patch '/books/:id', to: 'books#update'
  put '/books/:id', to: 'books#update'
  delete '/books/:id', to: 'books#destroy'

  #get '/home', to: 'pages#home'
  # post '/offers', to: 'offers#index'
  # post '/products', to: 'products#create'
  # put '/products/:id', to: 'products#update'
  # delete '/products/:id', to: 'products#destroy'
  # post '/bookings', to: 'bookings#create'
  # post '/reviews', to: 'reviews#create'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
 #get '/housings', to: 'housings#index', as: 'housings'

  # get 'pages/example', to: 'pages#example'
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/housing.rb
class Housing < ApplicationRecord
  belongs_to :user
  has_many :reviews, dependent: :destroy
  has_many :books
  has_one_attached :image



  def averagee_rating
    self.reviews.average(:rating).to_f.truncate(1)
  end



  def disabled_dates
    self.books.map do |book|
      {
        from: book.start_date.strftime("%Y-%m-%d"),
        to: book.end_date.strftime("%Y-%m-%d")
      }
    end
  end


  def first_available_dates
    disabled_dates = self.disabled_dates.sort_by { |range| range[:from] }
    available_dates = []
    date = Date.today

    while available_dates.size < 5
      if disabled_dates.empty? || date < DateTime.parse(disabled_dates.first[:from])
        available_dates << date
      elsif date > DateTime.parse(disabled_dates.first[:to])
        disabled_dates.shift
        next
      end
      date = date.next_day
    end

    available_dates
    
    { from: available_dates.first.strftime("%Y-%m-%d"), to: available_dates.last.strftime("%Y-%m-%d") }
  end
end

app/controllers/housings_controller.rb
class HousingsController < ApplicationController
  before_action :set_housing, only: %i[ show edit update destroy]
  skip_before_action :authenticate_user!, only: :show

  # GET /housings or /housings.json
  def index
    @housings = policy_scope(Housing)
    if params[:location].present?
      @housings = Housing.search_result(params[:location])
      p @housings
    end
  end

  # GET /housings/1 or /housings/1.json
  def show
    @review = Review.new
    @book = Book.new
  end

  # GET /housings/new
  def new
    @housing = Housing.new
    authorize @housing
  end

  # GET /housings/1/edit
  def edit
  end

  # POST /housings or /housings.json
  def create
    @housing = Housing.new(housing_params)
    @user_id =  current_user.id
    @housing.user_id = @user_id
    authorize @housing
    respond_to do |format|
      if @housing.save
        format.html { redirect_to housing_url(@housing), notice: "Housing was successfully created." }
        format.json { render :show, status: :created, location: @housing }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @housing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /housings/1 or /housings/1.json
  def update
    authorize @housing
    respond_to do |format|
      if @housing.update(housing_params)
        format.html { redirect_to housing_url(@housing), notice: "Housing was successfully updated." }
        format.json { render :show, status: :ok, location: @housing }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @housing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /housings/1 or /housings/1.json
  def destroy
    @housing.destroy
    authorize @housing
    respond_to do |format|
      format.html { redirect_to housings_url, notice: "Housing was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_housing
      @housing = Housing.find(params[:id])
      authorize @housing
      return @housing
    end

    # Only allow a list of trusted parameters through.
    def housing_params
      params.require(:housing).permit(:name, :user_id, :price, :amount_bathrooms, :amount_rooms, :msquare, :city, :state, :address)
    end
end

app/views/housings/_form.html.erb
<div class="w-100">
  <%= simple_form_for(@housing) do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <div class="form-inputs mt-5">
      <%= f.input :name, required: true, label: false, placeholder: "Housing Name" %>
      <%= f.input :image, as: :file, required: true, label: false, placeholder: "Image", id: "upload_widget", class: "cloudinary-button" %>
      <%= f.input :price, required: true, label: false, placeholder: "Price Per Night" %>
      <%= f.input :amount_bathrooms, required: true, label: false, placeholder: "Bathrooms" %>
      <%= f.input :amount_rooms, required: true, label: false, placeholder: "Rooms" %>
      <%= f.input :msquare, required: true, label: false, placeholder: "Squared Meters" %>
      <%= f.input :city, required: true, label: false, placeholder: "City" %>
      <%= f.input :state, required: true, label: false, placeholder: "State" %>
      <%= f.input :address, required: true, label: false, placeholder: "Address" %>
      <%= f.input :description, required: true, label: false, placeholder: "Description" %>


      <script src="https://widget.cloudinary.com/v2.0/global/all.js" type="text/javascript"></script>
      <script type="text/javascript">
      var widget = cloudinary.applyUploadWidget({
        dygidrhdn: 'demo',
        ml_default: 'blog_upload' },
        (error, result) => {
            if (!error && result && result.event === "success") {
              console.log('Done uploading..: ', result.info);
              }

          });

      document.getElementById("upload_widget").addEventListener("click", function(){
        myWidget.open();
      }, false);
        </script>
        </div>

    <div class="form-actions">
      <%= f.button :submit, class: "btn btn-primary text-white px-4 py-3 mt-3", style: 'border-radius: 15px;' %>
    </div>
  <% end %>
</div>

app/views/housings/_housing.html.erb
<div id="<%= dom_id housing %>">
  <p>
    <strong>Name:</strong>
    <%= housing.name %>
  </p>

  <p>
    <strong>User:</strong>
    <%= housing.user_id %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= housing.price %>
  </p>

  <p>
    <strong>Amount bathrooms:</strong>
    <%= housing.amount_bathrooms %>
  </p>

  <p>
    <strong>Amount rooms:</strong>
    <%= housing.amount_rooms %>
  </p>

  <p>
    <strong>Msquare:</strong>
    <%= housing.msquare %>
  </p>

  <p>
    <strong>City:</strong>
    <%= housing.city %>
  </p>

  <p>
    <strong>State:</strong>
    <%= housing.state %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= housing.address %>
  </p>

    <p>
    <strong>Address:</strong>
    <%= housing.description %>
  </p>

</div>

app/views/housings/edit.html.erb
<h1>Editing housing</h1>

<%= render "form", housing: @housing %>

<br>

<div>
  <%= link_to "Show this housing", @housing %> |
  <%= link_to "Back to housings", housings_path %>
</div>

app/views/housings/index.html.erb
<h1 class='mx-4 mb-5' style='margin-top: 75px;'>Your housings</h1>

<%# If there are not %>
<% if current_user.housings.length == 0 %>

<div class="d-flex m-4 card bg-white" style='border-radius: 15px;'>
  <div class="row">
    <%# Left %>
    <div class='col-6 p-5'>
      <svg class='mb-4 mt-3' width="32" height="32" viewBox="0 0 32 32" fill="none" xmlns="http://www.w3.org/2000/svg">
        <path d="M9.99849 3.08008L3.97559 10.6543L16.1289 26.2236L28.0368 10.6543L21.8922 3.08008H9.99849Z" fill="#F6D7DF"/>
        <path d="M30.1827 10.8954L16.0038 29.8989L1.81712 10.8954L30.1827 10.8954Z" stroke="#D03660" stroke-width="1.1916"/>
        <path d="M1.01465 10.6351L9.19495 1.10498H22.4728L30.9976 10.6391" stroke="#D03660" stroke-width="1.1916"/>
        <path d="M9.34033 1.29199L16.011 30.051L22.6679 1.29199" stroke="#D03660" stroke-width="1.1916"/>
      </svg>
      <h4>No houses posted...yet!</h4>
      <p class="text-secondary mt-1">
        Time to dust off your bags and start planning your next adventure.
      </p>
      <div class="btn btn-primary mt-4 mb-2 text-white w-50" style='border-radius: 15px;'>
        Become a host
      </div>
    </div>

    <%# Right %>
    <div class="col-6">
      <%= image_tag(asset_path('image 7.png'), class: 'w-100 h-100') %>
    </div>
  </div>
</div>
<% end %>


<%# If there are housings %>
<div class="m-4">
  <%# Tus housings %>
  <div class="row">
  <% @housings.each do |housing| %>
    <div class="col-3 mt-5">
      <%= render "shared/card", housing: housing %>
    </div>
  <% end %>
  </div>
</div>

app/views/housings/new.html.erb
<div class="form-container" style="margin: 96px 30%">
  <%= link_to "Back to housings", housings_path, class:'text-secondary', style:'text-decoration: none;' %>

  <h1 class='mt-5'>New housing</h1>

  <%= render "form", housing: @housing %>
</div>

app/views/housings/show.html.erb
<div id='back-to' class="d-flex m-4 gap-2 text-secondary">
  <% if policy(@housing).edit? %>
    <%= link_to "Edit this housing", edit_housing_path(@housing), class: 'text-secondary', style: 'text-decoration: none;' %> |
  <% end %>
  <% if policy(@housing).destroy? %>
    <%= button_to "Destroy this housing", @housing, method: :delete, class: 'text-secondary', style: 'text-decoration: none; border: none; background-color: transparent;' %> |
  <% end %>
  <%= link_to "Back to housings", housings_path, class: 'text-secondary', style: 'text-decoration: none;' %>
</div>


<p style="color: green"><%= notice %></p>
<div class="m-4">
  <h1> <%= @housing.name %> </h1>
  <div id='reviews-and-such' class="d-flex spacing-4">
    <div>
      <%# Stars %>
      <i class="fas fa-star star-gray"></i>
      <small><em class="text-muted"><%= @housing.averagee_rating %></em></small>

      <%# Spacer %>
      <small><em class="text-muted mx-2">·</em></small>

      <%# Number of reviews %>
      <small><em class="text-muted"><%= @housing.reviews.count %></em></small>
      <small><em class="text-muted">reviews</em></small>

      <%# Spacer %>
      <small><em class="text-muted mx-2">·</em></small>

      <%# Number of reviews %>
      <small><em class="text-muted"><%= @housing.city %>,</em></small>
      <small><em class="text-muted"><%= @housing.state %></em></small>
    </div>
  </div>

  <%# Image/s %>
  <div class="rounded mt-4">
    <div class="w-100 h-20 rounded-2" style='height: 75vh; background-image: url("<%= cl_image_path @housing.image.key %>"); background-size: cover; background-repeat: no-repeat; background-position: center center;'>
    </div>
  </div>

  <%# Information + Book %>
  <div class='mt-5 d-flex mb-4'>
    <%# Left %>
    <div class='left col-8' style='margin-right: 64px;'>
      <h3>Entire rental unit hosted by <%= @housing.user.first_name %></h3>
      <div>
        <%# Roos %>
        <small><em class="text-muted"><%= @housing.amount_rooms %></em></small>
        <small><em class="text-muted">rooms</em></small>

        <%# Spacer %>
        <small><em class="text-muted mx-2">·</em></small>

        <%# Bathrooms %>
        <small><em class="text-muted"><%= @housing.amount_bathrooms %></em></small>
        <small><em class="text-muted">bathrooms</em></small>

        <%# Spacer %>
        <small><em class="text-muted mx-2">·</em></small>

        <%# Number of reviews %>
        <small><em class="text-muted"><%= @housing.msquare %></em></small>
        <small><em class="text-muted">m2</em></small>
      </div>

      <%# Divider %>
      <hr class="hr my-4"/>

      <p class='text-secondary'><%= @housing.description %></p>
    </div>

    <%# Right %>
<% if current_user != @housing.user %>
    <div class='right border border-gray shadow p-4 w-100' style='border-radius: 10px;'>

      <%# Info de arriba %>
      <div class='d-flex justify-content-between mb-3'>
        <%# Precio por noche %>
        <div id="pricepernight" class='d-flex align-items-end gap-1'>
          <h5 style="margin-bottom: 4px;">$ <%= @housing.price %></span></h5>
          <p style="margin-bottom: 2px;">/ night</p>
        </div>

        <div id='reviews-and-such' class="d-flex spacing-4">
          <div>
            <%# Stars %>
            <i class="fas fa-star star-gray"></i>
            <small><em class="text-muted"><%= @housing.averagee_rating %></em></small>

            <%# Spacer %>
            <small><em class="text-muted mx-2">·</em></small>

            <%# Number of reviews %>
            <small><em class="text-muted"><%= @housing.reviews.count %></em></small>
            <small><em class="text-muted">reviews</em></small>
          </div>
        </div>
      </div>
      <div id='reviews-and-such' class="d-flex justify-content-center">
      <div class='w-100'>
        <%= simple_form_for [@housing, @book], data: { controller: 'flatpickr' ,action: 'click->flatpickr#calculateDays', flatpickr_disable_value: @housing.disabled_dates } do |f| %>
          <div>
            <%= f.input :start_date, as: :string,  type: :time, input_html: { value: @housing.first_available_dates[:from] ,class: 'form-control flatpickr-input', data: { flatpickr_target: 'startTime' } }, label: false, placeholder: 'Start date' %>
          </div>

          <div>
          <span class='d-none' type="text" data-flatpickr-target='housingPrice'>   <%= @housing.price  %> </span>
          </div>

          <div>
            <%= f.input :end_date, as: :string, type: :time , input_html: { value: @housing.first_available_dates[:to] ,class: 'form-control flatpickr-input', data: { flatpickr_target: 'endTime' } , id: 'end_time'}, label: false, placeholder: 'End date' %>
          </div>

          <div class="text-center w-100 mt-4">
            <%= f.button :submit, 'Schedule your appointment', class: 'btn btn-primary text-white py-3 w-100', style:'border-radius: 10px;' %>
          </div>



      <p class='w-100 text-center text-secondary mt-4'>You won't be charged yet.</p>

      <%# Cálculos %>

      <%# Precio por noche %>
      <div class='d-flex justify-content-between mt-4'>
        <p>$<%= @housing.price %> x <p><span type="text" data-flatpickr-target='dayCount' >5</span></p>noches</p>
        <p> $<span type="text" data-flatpickr-target='totalDays'></p>
      </div>

      <%# Descuento semanal %>
      <div class='d-flex justify-content-between'>
        <p>Fee</p>
        <p class='text-success' data-flatpickr-target='fee' ></p>
      </div>

      <%# Divider %>
      <hr class="hr my-4"/>

      <%# Total %>
      <div class='d-flex justify-content-between'>
        <%= f.input :total_price, as: :string, input_html: { class: 'd-none' ,value: '' , data: { flatpickr_target: 'totalPrice' }} %>
        <h6>Total</h6>
        <h6  data-flatpickr-target='total' ></h6>
        <% end %>

      </div>
    </div>
  </div>
</div>
  <% end %>
</div>


<%# Divider %>
<hr class="hr my-5"/>

<%# Reviews Container %>
<div>
  <%# Reviews %>
  <div id='reviews-and-such' class="d-flex spacing-4 mb-2">
    <div>
      <%# Stars %>
      <i class="fas fa-star star-gray"></i>
      <small><em class="text-muted"><%= @housing.averagee_rating %></em></small>

      <%# Spacer %>
      <small><em class="text-muted mx-2">·</em></small>

      <%# Number of reviews %>
      <small><em class="text-muted"><%= @housing.reviews.count %></em></small>
      <small><em class="text-muted">reviews</em></small>
    </div>
  </div>

  <% if @housing.reviews.empty?  %>
    <small><em class="text-muted">Be the first one to review this list</em></small>
  <% end %>
  <% @housing.reviews.each do |review| %>
    <div>
      <% review.rating.times do %>
        <i class="fas fa-star star-yellow"></i>
      <% end %>
      <small><em class="text-muted"><%= distance_of_time_in_words_to_now(review.created_at) %> ago</em></small>
      <p><%= review.content %></p>
    </div>
    <hr>
  <% end %>
<% if current_user != @housing.user %>
    </div>
    <div>
      <div class="bg-white rounded py-3">
        <h5>Add your review</h5>
        <%= simple_form_for [@housing, @review] do |f| %>
          <%= f.input :content, placeholder: "Write your review here...", label: false, class: "form-control pt-4" %>

          <%= f.input :rating, as: :select, collection: (1..5).to_a, required: true, prompt: "What's your rating",
                      input_html: { class: "form-select pt-4", data: { controller: "star-rating" } }, label: false %>

          <%= f.submit "Submit", class: "btn btn-primary text-white py-3 px-5 mt-4 rounded-10", style: 'border-radius: 15px;' %>
        <% end %>
      </div>
    </div>
  </div>
<% end %>
</div>